version: '3'

services:
  web:
    build: .
    ports:
      - "80:5001"
    environment:
      - FLASK_APP=front_end
      - FLASK_ENV=production
    command: gunicorn --bind 0.0.0.0:5001 front_end:index

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
